name: JDK 11 Build

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: xformativ-nexus # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          settings-path: ${{ github.workspace }} # location for the settings.xml file
        env:
          MAVEN_USERNAME: ${{ secrets.XFORMATIV_MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.XFORMATIV_MAVEN_PASSWORD }}
      - name: Build with Maven
        run: mvn -B clean compile test package --file pom.xml -s ${{ github.workspace }}/settings.xml
        env:
          MAVEN_USERNAME: ${{ secrets.XFORMATIV_MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.XFORMATIV_MAVEN_PASSWORD }}
      - name: Code Coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=xformativ_shapetrees-java