name: JDK 11 Build

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: xformativ-nexus # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          settings-path: ${{ github.workspace }} # location for the settings.xml file
        env:
          MAVEN_USERNAME: ${{ secrets.XFORMATIV_MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.XFORMATIV_MAVEN_PASSWORD }}
      - name: Build with Maven and Analyze with Sonar
        run: mvn -B clean compile test package verify --file pom.xml -s ${{ github.workspace }}/settings.xml org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=xformativ_shapetrees-java
        env:
          MAVEN_USERNAME: ${{ secrets.XFORMATIV_MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.XFORMATIV_MAVEN_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}